server:
  port: 2000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jfa_lcs?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 222000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG



sms:
  account: I2223721
  password: YfIc1ipL3h12c6
  url: http://intapi.253.com/send/json
  template: 【吉富通】您的验证码为：{0}，该验证码5分钟内有效，请勿泄露给他人。
export:
  cron: 1 * * * * ?
  directory: o:\\
