server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.0.7:3306/motse?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 222000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
#    static-path-pattern: /*


algorithm:
  parity: 1

clear:
  cron: '0 0 0 * * ?'